version: '3.1'
services:
  app:
    container_name: docker-image-mongo
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile-local
    ports: 
      - "80:3000"
      - "5050:5000"
    links:
      - mongo
    volumes:
      - /Users/maxinran/Documents/ACADEMIC/Programming/xinran_blog:/usr/src/app
      - /usr/src/app/server/node_modules
      - /usr/src/app/server/client/node_modules
  mongo:
    container_name: mongo
    image: mongo:4.2.1
    ports:
      - '27017:27017'