version: '3'
services:
  app:
    container_name: docker-image-mongo
    restart: always
    build: .
    ports: 
      - '80:3000'
    links:
      - mongo
  mongo:
    container_name: mongo：4.2.1
    image: mongo
    ports:
      - '27017:27017'