FROM node:13.1.0

WORKDIR /usr/src/app/server

COPY server/package*.json ./

RUN npm install && npm install mongoose -g 

COPY server/client/package*.json ./client/

RUN npm install --prefix client

WORKDIR /usr/src/app

COPY . .

EXPOSE 3000
EXPOSE 5000

WORKDIR /usr/src/app/server

CMD ["npm", "run", "dev"]